# ===============
#
# The reason this file exists is to ensure that people who still have the
# SASS extensions installed do not get false linting in thier editors.
#
# @since 10/15/20
# @author Aubrey Portwood <aubrey@webdevstudios.com>
#
# ================

files:
  ignore:
    - "**/*.s+(a|c)ss"
    - "**/*.css"
